#!/system/bin/sh

ln -sf /system/xbin/toybox acpi
ln -sf /system/xbin/toybox base64
ln -sf /system/xbin/toybox basename
ln -sf /system/xbin/toybox blkid
ln -sf /system/xbin/toybox blockdev
ln -sf /system/xbin/toybox bzcat
ln -sf /system/xbin/toybox cal
ln -sf /system/xbin/toybox cat
ln -sf /system/xbin/toybox chattr
ln -sf /system/xbin/toybox chgrp
ln -sf /system/xbin/toybox chmod
ln -sf /system/xbin/toybox chown
ln -sf /system/xbin/toybox chroot
ln -sf /system/xbin/toybox chvt
ln -sf /system/xbin/toybox cksum
ln -sf /system/xbin/toybox clear
ln -sf /system/xbin/toybox cmp
ln -sf /system/xbin/toybox comm
ln -sf /system/xbin/toybox count
ln -sf /system/xbin/toybox cp
ln -sf /system/xbin/toybox cpio
ln -sf /system/xbin/toybox cut
ln -sf /system/xbin/toybox date
ln -sf /system/xbin/toybox df
ln -sf /system/xbin/toybox dirname
ln -sf /system/xbin/toybox dmesg
ln -sf /system/xbin/toybox dos2unix
ln -sf /system/xbin/toybox du
ln -sf /system/xbin/toybox echo
ln -sf /system/xbin/toybox egrep
ln -sf /system/xbin/toybox eject
ln -sf /system/xbin/toybox env
ln -sf /system/xbin/toybox expand
ln -sf /system/xbin/toybox factor
ln -sf /system/xbin/toybox false
ln -sf /system/xbin/toybox fgrep
ln -sf /system/xbin/toybox find
ln -sf /system/xbin/toybox free
ln -sf /system/xbin/toybox freeramdisk
ln -sf /system/xbin/toybox fsfreeze
ln -sf /system/xbin/toybox fstype
ln -sf /system/xbin/toybox grep
ln -sf /system/xbin/toybox groups
ln -sf /system/xbin/toybox halt
ln -sf /system/xbin/toybox head
ln -sf /system/xbin/toybox help
ln -sf /system/xbin/toybox hostname
ln -sf /system/xbin/toybox id
ln -sf /system/xbin/toybox ifconfig
ln -sf /system/xbin/toybox inotifyd
ln -sf /system/xbin/toybox insmod
ln -sf /system/xbin/toybox install
ln -sf /system/xbin/toybox kill
ln -sf /system/xbin/toybox killall
ln -sf /system/xbin/toybox killall5
ln -sf /system/xbin/toybox link
ln -sf /system/xbin/toybox ln
ln -sf /system/xbin/toybox login
ln -sf /system/xbin/toybox logname
ln -sf /system/xbin/toybox losetup
ln -sf /system/xbin/toybox ls
ln -sf /system/xbin/toybox lsattr
ln -sf /system/xbin/toybox lsmod
ln -sf /system/xbin/toybox lspci
ln -sf /system/xbin/toybox lsusb
ln -sf /system/xbin/toybox makedevs
ln -sf /system/xbin/toybox md5sum
ln -sf /system/xbin/toybox mix
ln -sf /system/xbin/toybox mkdir
ln -sf /system/xbin/toybox mkfifo
ln -sf /system/xbin/toybox mknod
ln -sf /system/xbin/toybox mkpasswd
ln -sf /system/xbin/toybox mkswap
ln -sf /system/xbin/toybox mktemp
ln -sf /system/xbin/toybox modinfo
ln -sf /system/xbin/toybox mount
ln -sf /system/xbin/toybox mountpoint
ln -sf /system/xbin/toybox mv
ln -sf /system/xbin/toybox nbd-client
ln -sf /system/xbin/toybox nc
ln -sf /system/xbin/toybox netcat
ln -sf /system/xbin/toybox nice
ln -sf /system/xbin/toybox nl
ln -sf /system/xbin/toybox nohup
ln -sf /system/xbin/toybox od
ln -sf /system/xbin/toybox oneit
ln -sf /system/xbin/toybox partprobe
ln -sf /system/xbin/toybox passwd
ln -sf /system/xbin/toybox paste
ln -sf /system/xbin/toybox patch
ln -sf /system/xbin/toybox pidof
ln -sf /system/xbin/toybox pivot_root
ln -sf /system/xbin/toybox pmap
ln -sf /system/xbin/toybox poweroff
ln -sf /system/xbin/toybox printenv
ln -sf /system/xbin/toybox printf
ln -sf /system/xbin/toybox pwd
ln -sf /system/xbin/toybox pwdx
ln -sf /system/xbin/toybox readahead
ln -sf /system/xbin/toybox readlink
ln -sf /system/xbin/toybox realpath
ln -sf /system/xbin/toybox reboot
ln -sf /system/xbin/toybox renice
ln -sf /system/xbin/toybox rev
ln -sf /system/xbin/toybox rfkill
ln -sf /system/xbin/toybox rm
ln -sf /system/xbin/toybox rmdir
ln -sf /system/xbin/toybox rmmod
ln -sf /system/xbin/toybox sed
ln -sf /system/xbin/toybox seq
ln -sf /system/xbin/toybox setsid
ln -sf /system/xbin/toybox sha1sum
ln -sf /system/xbin/toybox sleep
ln -sf /system/xbin/toybox sort
ln -sf /system/xbin/toybox split
ln -sf /system/xbin/toybox stat
ln -sf /system/xbin/toybox strings
ln -sf /system/xbin/toybox su
ln -sf /system/xbin/toybox swapoff
ln -sf /system/xbin/toybox swapon
ln -sf /system/xbin/toybox switch_root
ln -sf /system/xbin/toybox sync
ln -sf /system/xbin/toybox sysctl
ln -sf /system/xbin/toybox tac
ln -sf /system/xbin/toybox tail
ln -sf /system/xbin/toybox taskset
ln -sf /system/xbin/toybox tee
ln -sf /system/xbin/toybox time
ln -sf /system/xbin/toybox timeout
ln -sf /system/xbin/toybox touch
ln -sf /system/xbin/toybox true
ln -sf /system/xbin/toybox truncate
ln -sf /system/xbin/toybox tty
ln -sf /system/xbin/toybox umount
ln -sf /system/xbin/toybox uname
ln -sf /system/xbin/toybox uniq
ln -sf /system/xbin/toybox unix2dos
ln -sf /system/xbin/toybox unlink
ln -sf /system/xbin/toybox unshare
ln -sf /system/xbin/toybox uptime
ln -sf /system/xbin/toybox usleep
ln -sf /system/xbin/toybox uudecode
ln -sf /system/xbin/toybox uuencode
ln -sf /system/xbin/toybox vconfig
ln -sf /system/xbin/toybox vmstat
ln -sf /system/xbin/toybox w
ln -sf /system/xbin/toybox wc
ln -sf /system/xbin/toybox which
ln -sf /system/xbin/toybox who
ln -sf /system/xbin/toybox whoami
ln -sf /system/xbin/toybox xargs
ln -sf /system/xbin/toybox yes
